server:
  port: 8080
  servlet:
    session:
      timeout: 3600s
spring:
  application:
    name: boot-layui-demo
  datasource:
    url: jdbc:mysql://139.159.177.48:3306/my_default_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: zhaolei
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 100
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

auth:
  skip:
    antMatchers:
      /**/favicon.ico,
      /swagger-resources/**,
      /webjars/**,
      /v2/**,
      /swagger-ui.html/**
